# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - feature/30-working-fmt
pool:
  vmImage: ubuntu-latest


resources:
  repositories:
    - repository: central
      type: git
      name: UAEDevOps/CentralRepo
      ref: refs/heads/main

stages:
  - template: .\entrypoint\terraform\tf_plan.yaml@central
#  - template: .\entrypoint\terraform\tf_validate.yaml@central
  - template: .\entrypoint\terraform\tf_apply.yaml@central
