# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: central
      type: git
      name: UAEDevOps/11-30-central-repo
      ref: refs/heads/main

stages:
  - template: .\deploy\ci.yaml@central