parameters:
  - name: type
    type: string

stages:
  - stage: BuildImage
    # condition: and(succeeded(), ne("${{ parameters.type }}", "rabbitmq"))
    displayName: 'AKS Build & Push to ACR'
    jobs:
      - job: BuildImage
        displayName: BuildImage
        pool:
          vmImage: ubuntu-latest
        container: beginneracademy/azdoagent:1.4
        steps:
          - checkout: self
          - bash: |
              ls -lrt $$(System.DefaultWorkingDirectory)/
              echo JAVA_HOME is $JAVA_HOME
              pwd
              java --version
              echo "deploying ${{ parameters.type }}"
            name: "ls"

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: "acr"

          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              Dockerfile: '**/Dockerfile'
              repository: "${{ parameters.type }}" 
              tags: "latest"