parameters:
  - name: tag
    type: string
stages:
  - stage: BuildImage
    displayName: 'AKS Build & Push to ACR'
    variables:
      - template: ../variable/built-variables.yaml
      - template: ../variable/deploy-variables.yaml
    jobs:
      - job: BuildImage
        displayName: BuildImage
        pool:
          vmImage: ubuntu-latest
        container: beginneracademy/azdoagent:1.4
        steps:
          - bash: |
              echo "deployment boolean value is" ${{ variables.deployment }}
              ls -lrt $(System.DefaultWorkingDirectory)/target/
              echo JAVA_HOME is $JAVA_HOME
              java --version
            name: "key_Value_boolean"

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: "acr"

          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: "${{ variables.acr_front_image_repository }}"  # username/contosoRepository for DockerHub
              tags: "latest"


