{{- if eq .Values.useRabbitMQ true }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
data:
  RABBITMQ_DEFAULT_USER: "{{ .Values.orderService.queueUsername | b64enc  }}"
  RABBITMQ_DEFAULT_PASS: "{{ .Values.orderService.queuePassword | b64enc  }}"
{{- end }}